version: "3.8"
services:
  # bind mount example
  linuxgsm-tu-bind:
    image: gameservermanagers/gameserver:tu
    # image: ghcr.io/gameservermanagers/gameserver:tu
    container_name: tuserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/tuserver:/data
    network_mode: host

  # volume example
  linuxgsm-tu-volume:
    image: gameservermanagers/gameserver:tu
    # image: ghcr.io/gameservermanagers/gameserver:tu
    container_name: tuserver
    restart: unless-stopped
    volumes:
      - linuxgsm-tu:/data
    network_mode: host

volumes:
  linuxgsm-tu:
