version: "3.8"
services:
  # bind mount example
  linuxgsm-cscz-bind:
    image: gameservermanagers/gameserver:cscz
    # image: ghcr.io/gameservermanagers/gameserver:cscz
    container_name: csczserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/csczserver:/data
    network_mode: host

  # volume example
  linuxgsm-cscz-volume:
    image: gameservermanagers/gameserver:cscz
    # image: ghcr.io/gameservermanagers/gameserver:cscz
    container_name: csczserver
    restart: unless-stopped
    volumes:
      - linuxgsm-cscz:/data
    network_mode: host

volumes:
  linuxgsm-cscz:
