version: "3.8"
services:
  # bind mount example
  linuxgsm-css-bind:
    image: gameservermanagers/gameserver:css
    # image: ghcr.io/gameservermanagers/gameserver:css
    container_name: cssserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/cssserver:/data
    network_mode: host

  # volume example
  linuxgsm-css-volume:
    image: gameservermanagers/gameserver:css
    # image: ghcr.io/gameservermanagers/gameserver:css
    container_name: cssserver
    restart: unless-stopped
    volumes:
      - linuxgsm-css:/data
    network_mode: host

volumes:
  linuxgsm-css:
