version: "3.8"
services:
  # bind mount example
  linuxgsm-vints-bind:
    image: gameservermanagers/gameserver:vints
    # image: ghcr.io/gameservermanagers/gameserver:vints
    container_name: vintsserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/vintsserver:/data
    network_mode: host

  # volume example
  linuxgsm-vints-volume:
    image: gameservermanagers/gameserver:vints
    # image: ghcr.io/gameservermanagers/gameserver:vints
    container_name: vintsserver
    restart: unless-stopped
    volumes:
      - linuxgsm-vints:/data
    network_mode: host

volumes:
  linuxgsm-vints:
