version: "3.8"
services:
  # bind mount example
  linuxgsm-dods-bind:
    image: gameservermanagers/gameserver:dods
    # image: ghcr.io/gameservermanagers/gameserver:dods
    container_name: dodsserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/dodsserver:/data
    network_mode: host

  # volume example
  linuxgsm-dods-volume:
    image: gameservermanagers/gameserver:dods
    # image: ghcr.io/gameservermanagers/gameserver:dods
    container_name: dodsserver
    restart: unless-stopped
    volumes:
      - linuxgsm-dods:/data
    network_mode: host

volumes:
  linuxgsm-dods:
