version: "3.8"
services:
  # bind mount example
  linuxgsm-pvr-bind:
    image: gameservermanagers/gameserver:pvr
    # image: ghcr.io/gameservermanagers/gameserver:pvr
    container_name: pvrserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/pvrserver:/data
    network_mode: host

  # volume example
  linuxgsm-pvr-volume:
    image: gameservermanagers/gameserver:pvr
    # image: ghcr.io/gameservermanagers/gameserver:pvr
    container_name: pvrserver
    restart: unless-stopped
    volumes:
      - linuxgsm-pvr:/data
    network_mode: host

volumes:
  linuxgsm-pvr:
