version: "3.8"
services:
  # bind mount example
  linuxgsm-cc-bind:
    image: gameservermanagers/gameserver:cc
    # image: ghcr.io/gameservermanagers/gameserver:cc
    container_name: ccserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/ccserver:/data
    network_mode: host

  # volume example
  linuxgsm-cc-volume:
    image: gameservermanagers/gameserver:cc
    # image: ghcr.io/gameservermanagers/gameserver:cc
    container_name: ccserver
    restart: unless-stopped
    volumes:
      - linuxgsm-cc:/data
    network_mode: host

volumes:
  linuxgsm-cc:
