version: "3.8"
services:
  # bind mount example
  linuxgsm-armar-bind:
    image: gameservermanagers/gameserver:armar
    # image: ghcr.io/gameservermanagers/gameserver:armar
    container_name: armarserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/armarserver:/data
    network_mode: host

  # volume example
  linuxgsm-armar-volume:
    image: gameservermanagers/gameserver:armar
    # image: ghcr.io/gameservermanagers/gameserver:armar
    container_name: armarserver
    restart: unless-stopped
    volumes:
      - linuxgsm-armar:/data
    network_mode: host

volumes:
  linuxgsm-armar:
