version: "3.8"
services:
  # bind mount example
  linuxgsm-kf-bind:
    image: gameservermanagers/gameserver:kf
    # image: ghcr.io/gameservermanagers/gameserver:kf
    container_name: kfserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/kfserver:/data
    network_mode: host

  # volume example
  linuxgsm-kf-volume:
    image: gameservermanagers/gameserver:kf
    # image: ghcr.io/gameservermanagers/gameserver:kf
    container_name: kfserver
    restart: unless-stopped
    volumes:
      - linuxgsm-kf:/data
    network_mode: host

volumes:
  linuxgsm-kf:
