version: "3.8"
services:
  # bind mount example
  linuxgsm-ut2k4-bind:
    image: gameservermanagers/gameserver:ut2k4
    # image: ghcr.io/gameservermanagers/gameserver:ut2k4
    container_name: ut2k4server
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/ut2k4server:/data
    network_mode: host

  # volume example
  linuxgsm-ut2k4-volume:
    image: gameservermanagers/gameserver:ut2k4
    # image: ghcr.io/gameservermanagers/gameserver:ut2k4
    container_name: ut2k4server
    restart: unless-stopped
    volumes:
      - linuxgsm-ut2k4:/data
    network_mode: host

volumes:
  linuxgsm-ut2k4:
