version: "3.8"
services:
  # bind mount example
  linuxgsm-cod2-bind:
    image: gameservermanagers/gameserver:cod2
    # image: ghcr.io/gameservermanagers/gameserver:cod2
    container_name: cod2server
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/cod2server:/data
    network_mode: host

  # volume example
  linuxgsm-cod2-volume:
    image: gameservermanagers/gameserver:cod2
    # image: ghcr.io/gameservermanagers/gameserver:cod2
    container_name: cod2server
    restart: unless-stopped
    volumes:
      - linuxgsm-cod2:/data
    network_mode: host

volumes:
  linuxgsm-cod2:
