version: "3.8"
services:
  # bind mount example
  linuxgsm-bt-bind:
    image: gameservermanagers/gameserver:bt
    # image: ghcr.io/gameservermanagers/gameserver:bt
    container_name: btserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/btserver:/data
    network_mode: host

  # volume example
  linuxgsm-bt-volume:
    image: gameservermanagers/gameserver:bt
    # image: ghcr.io/gameservermanagers/gameserver:bt
    container_name: btserver
    restart: unless-stopped
    volumes:
      - linuxgsm-bt:/data
    network_mode: host

volumes:
  linuxgsm-bt:
