version: "3.8"
services:
  # bind mount example
  linuxgsm-mc-bind:
    image: gameservermanagers/gameserver:mc
    # image: ghcr.io/gameservermanagers/gameserver:mc
    container_name: mcserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/mcserver:/data
    network_mode: host

  # volume example
  linuxgsm-mc-volume:
    image: gameservermanagers/gameserver:mc
    # image: ghcr.io/gameservermanagers/gameserver:mc
    container_name: mcserver
    restart: unless-stopped
    volumes:
      - linuxgsm-mc:/data
    network_mode: host

volumes:
  linuxgsm-mc:
