version: "3.8"
services:
  # bind mount example
  linuxgsm-q3-bind:
    image: gameservermanagers/gameserver:q3
    # image: ghcr.io/gameservermanagers/gameserver:q3
    container_name: q3server
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/q3server:/data
    network_mode: host

  # volume example
  linuxgsm-q3-volume:
    image: gameservermanagers/gameserver:q3
    # image: ghcr.io/gameservermanagers/gameserver:q3
    container_name: q3server
    restart: unless-stopped
    volumes:
      - linuxgsm-q3:/data
    network_mode: host

volumes:
  linuxgsm-q3:
