version: "3.8"
services:
  # bind mount example
  linuxgsm-hcu-bind:
    image: gameservermanagers/gameserver:hcu
    # image: ghcr.io/gameservermanagers/gameserver:hcu
    container_name: hcuserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/hcuserver:/data
    network_mode: host

  # volume example
  linuxgsm-hcu-volume:
    image: gameservermanagers/gameserver:hcu
    # image: ghcr.io/gameservermanagers/gameserver:hcu
    container_name: hcuserver
    restart: unless-stopped
    volumes:
      - linuxgsm-hcu:/data
    network_mode: host

volumes:
  linuxgsm-hcu:
