services:
  dashboard:  # Defines the service named "flask-app"
    image: ghcr.io/loadingstill/webgsm:latest  # Pulls the pre-built image from GitHub Container Registry
    container_name: WebGSM-Dashboard
    build:
      context: .  # Build the image using the Dockerfile in the current directory
      dockerfile: Dockerfile  # Specifies the name of the Dockerfile (optional if named 'Dockerfile')
    ports:
      - "5050:5050"  # Map container port 5000 to local port 5000, allowing access to the Flask app from the browser at localhost:5000
    restart: always  # Ensure the container always restarts if it stops or crashes
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "debug"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Mount the Docker socket to allow container to control Docker
    environment:
      - FLASK_ENV=development