services:
  dashboard:
    image: ghcr.io/loadingstill/webgsm:latest  # Pulls the pre-built image from GitHub Container Registry
    container_name: WebGSM-Dashboard
    ports:
      - "5050:5050"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "debug"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Mount the Docker socket to allow container to control Docker
    environment:
      - FLASK_ENV=development