name: WebGSM-Docker.yml # Build and Publish

on:
  push:
    branches:
      - main # Runs on pushes to the 'main' branch
  pull_request: # Optional: Run for pull requests to test

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner | toLower() }}/webgsm:latest
            ghcr.io/${{ github.repository_owner | toLower() }}/webgsm:${{ github.run_number }}

